# Generated by Django 6.0.5 on 2026-06-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='date_earned',
        ),
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, help_text='Upload PDF or Image of the certificate', null=True, upload_to='certificates/'),
        ),
    ]
